# Generated by Django 6.0.3 on 2026-03-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_answer_auto_feedback_answer_subjective_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject_tag',
            field=models.CharField(default='common', max_length=50),
        ),
        migrations.AddField(
            model_name='questionbankitem',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='questionbankitem',
            name='subject_tag',
            field=models.CharField(default='common', max_length=50),
        ),
        migrations.AddField(
            model_name='questionbankitem',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
