# Generated by Django 6.0.3 on 2026-03-30 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_exam_control_status_alter_userprofile_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_snapshot', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('purpose', models.CharField(choices=[('reset_password', 'Reset Password'), ('bind_email', 'Bind Email')], max_length=30)),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'purpose', '-created_at'], name='demo_emailv_email_ecb7c8_idx'), models.Index(fields=['username_snapshot', 'purpose', '-created_at'], name='demo_emailv_usernam_48bd45_idx')],
            },
        ),
    ]
