# Generated by Django 6.0.3 on 2026-03-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='selected_options',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_options',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='questionbankitem',
            name='correct_options',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Single Choice'), ('multiple', 'Multiple Choice'), ('judge', 'True or False'), ('blank', 'Fill in Blank'), ('short', 'Short Answer'), ('subjective', 'Subjective (Legacy)')], default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionbankitem',
            name='question_type',
            field=models.CharField(choices=[('single', 'Single Choice'), ('multiple', 'Multiple Choice'), ('judge', 'True or False'), ('blank', 'Fill in Blank'), ('short', 'Short Answer'), ('subjective', 'Subjective (Legacy)')], default='single', max_length=20),
        ),
    ]
