# Generated by Django 6.0.3 on 2026-03-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_answer_selected_options_question_correct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options_json',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questionbankitem',
            name='options_json',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Single Choice'), ('multiple', 'Multiple Choice'), ('judge', 'True or False'), ('short', 'Short Answer'), ('subjective', 'Subjective (Legacy)')], default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionbankitem',
            name='question_type',
            field=models.CharField(choices=[('single', 'Single Choice'), ('multiple', 'Multiple Choice'), ('judge', 'True or False'), ('short', 'Short Answer'), ('subjective', 'Subjective (Legacy)')], default='single', max_length=20),
        ),
    ]
