from django.urls import path

from .views import (
    auth_login,
    auth_me,
    auth_register,
    course_stats,
    course_students,
    courses,
    exam_detail,
    exam_grading_overview,
    exam_submissions,
    exams,
    grade_submission,
    hello_world,
    my_submissions,
    question_bank,
    question_bank_detail,
    question_bank_meta,
    release_exam_results,
    students,
    submit_exam,
)

urlpatterns = [
    path('hello/', hello_world),
    path('auth/register/', auth_register),
    path('auth/login/', auth_login),
    path('auth/me/', auth_me),
    path('students/', students),
    path('courses/', courses),
    path('courses/<int:course_id>/students/', course_students),
    path('courses/<int:course_id>/stats/', course_stats),
    path('question-bank/meta/', question_bank_meta),
    path('question-bank/', question_bank),
    path('question-bank/<int:item_id>/', question_bank_detail),
    path('exams/', exams),
    path('exams/<int:exam_id>/', exam_detail),
    path('exams/<int:exam_id>/submit/', submit_exam),
    path('exams/<int:exam_id>/grading/', exam_grading_overview),
    path('exams/<int:exam_id>/release-results/', release_exam_results),
    path('exams/<int:exam_id>/submissions/', exam_submissions),
    path('submissions/<int:submission_id>/grade/', grade_submission),
    path('submissions/mine/', my_submissions),
]
